title: Mark Swatosh
logo: /assets/img/mark.jpg
description: Mark Swatosh is a software engineer with an interest in green building.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
