title: Mark Swatosh
logo: /assets/img/mark.jpg
description: Hello! I'm Mark Swatosh, a software engineer with experience building microservice and serverless platforms for enterprise Java Applications. In 2019 I designed a solar powered Net-Zero house which I live in with my wife and our dog.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
